### ISSUE TITLE
zIndex of editors

### ISSUE THREAD

**Issue by IOZD** [TGFTech/angular-cesium#191]
**Intended outcome:**
I try to edit specific polygon that is covered by other polygons and drag it from place to place - the Intended outcome is that the chosen polygon will be dragged;

**Actual outcome:**
the chosen polygon cant be dragged because it is covered by other polygons.

**How to reproduce the issue:**
create 3 new polygons with the same size and locate them in the same position,,
try to edit the second polygon and move it - it won't work.

**Version**
- angular-cesium@0.0.39

**Comment by tomermoshe** [comment]
z-index is a general problem with cesium and is very poorly supported if at all.
In general, I suggest using the height property in order to set different z-index to map objects.
Our editable map objects are built using multiple graphics that together, act as a single map object. This raises difficulties with changing the z-index of the whole editable map object because the different graphics that are used to build it are rendered differently and don't have a single consistent property that changes their z-index. We plan to create a better support for the z-index issue in the future. In the meantime you can maybe hide all the editable object beside the last editable object created or something similar.
